### ISSUE TITLE
تحويل الاكواد الانجليزية من اليسار لليمين

### ISSUE THREAD

**Issue by AhmedElTabarani** [imAbdelhadi/nextjs-arabic-handbook#1]
<div dir = rtl>

جميع الاكواد الانجليزية في الملف تكون بهذا الشكل 

![image](https://user-images.githubusercontent.com/69223584/135726354-4515837c-42bd-4f01-9b54-a9d0196f2053.png)
 
 حل الأمر بسيط وهو وضع 
 
 `<div dir = ltr>`
<div dir = ltr>

```js
const Index = () => (
  <div>
    <h1>Home page</h1>
  </div>
);

export default Index;

```
</div>

`</div>`

ثم اكمال الكتابة العربية من اليمين لليسار بشكل اعتيادي
الامر ذاته مع اكواد الكونسول

**Comment by imAbdelhadi** [comment]
<div dir = rtl>
هل يمكن أن تعمل pull request وتساعدني في تصحيحها؟

**Comment by AhmedElTabarani** [comment]
ليس لدي مشكلة

**Comment by AhmedElTabarani** [comment]
<div dir = rtl>

![image](https://user-images.githubusercontent.com/69223584/135851090-e076b9df-9633-48a9-91c3-c9356e695d65.png)

لاحظت وجود كلمات ليس بها نهاية ` لذا اقوم باكمالها
الامر نفسه في المدونه وجت هب

هل الريبو مرتبط بالمقال في المدونة بشكل تلقائي ؟
اردت التنبيه تحسبنا بان المقال في المدونة ليست مرتبطًا بالمقال في هذا الريبو

**Comment by imAbdelhadi** [comment]
<div dir = rtl>
جميل، نعم توجد بعض الأخطاء الصغيرة التي لم أنتبه لها.

> هل الريبو مرتبط بالمقال في المدونة بشكل تلقائي ؟

لا، كل واحدة على حدى. لكن نسخ ولصق يصيران بنفس المحتوى.

**Comment by AhmedElTabarani** [comment]
<div dir="rtl">

حسنا انا اقوم باصلاح جميع المشاكل المرتبطة بوجود اللغة الانجليزية والعربية

سأحاول ان اوضح هنا كل الامور التى واجهتني وطريقة حلها او تجنبها لكي تستطيع التعامل معها فيما بعد  

![image](https://user-images.githubusercontent.com/69223584/135852820-1d69fea2-93a1-46bd-8d8d-8984ff3b9855.png)

هنا احيانا عندما نستعمل rtl مع  ` ورموز تقلب الجملة الانجليزية هكذا

الحل باستعمال 

<div dir="ltr">

```html
<span dir ="ltr"> `--example` </span>
```
</div>

واحيانا بعد قيامنا بهذا تلتصق الكلمة الانجليزية مع العربية دون وجود مسافة ولا يمكننا وضع مسافة 
لذا نستعمل &nbsp;

لا داعي للرد لانني قد اكتب مشاكل عدة وطرق حلها بغرض ان تتجنبها في المستقبل
